### ISSUE TITLE
Trying to poke something with a null

### ISSUE THREAD

**Issue by VegaDeftwing** [noisedeck/noisedeck-docs#16]
![consoleerror](https://user-images.githubusercontent.com/11283620/115136287-70dfb100-9fe4-11eb-8539-2c1fc92c28c8.png)

Error found on Vivaldi version 3.7.2218.55 (Stable channel) (64-bit), Arch Linux with the 5.11.15-zen1-2-zen kernel. This build of Vivaldi is using V8 8.9.255.25

I set a breakpoint on sketch.js:2325 and never saw it trying to work with a null, I *think* it's happening on page load, and works fine after the initial random settings have been selected. **There is no actual visible or user impacting issue here**, just thought you might want to see it.

I also tried it in Firefox 87.0 and Chromium 90.0.4430.72 on the same system, but the issue does not appear at all. I similarly set a breakpoint, and never encountered a null, but I am not a web dev and am not sure how to set a breakpoint for page load. ╮(─▽─)╭

Not to put 2 issues in 1, but I also saw a 404 on https://cdn.jsdelivr.net/npm/p5@1.2.0/lib/addons/p5.sound.min.js.map on all browsers, though can load it fine if I navigate to that address without `map` on the end.

**Comment by jesshewitt** [comment]
Thanks for the report - I've been seeing that too (Chrome/Windows 10). It happens at startup frequently, but doesn't seem to be a show-stopper. I'm in the process of rewriting the core of Noisedeck to remove the p5/p5.sound dependencies, so hopefully that will address both of these issues.

**Comment by jesshewitt** [comment]
This issue is resolved with the refactor removing the dependency on p5.sound
