### ISSUE TITLE
all-seeing-eye module hidden / hide module list not populated

### ISSUE THREAD

**Issue by j4s0n-c** [noisedeck/noisedeck-docs#23]
During my first login to pro the 'all-seeing-eye' module is hidden and the 'hide modules' list in settings is empty. Once I log out and in again the 'hide modules' list is populated and I have to ctrl-click to deselect 'all-seeing-eye' and save for it to show up in the main interface. Tested on Chrome and Edge, same behavior.
![hide_list_not_populated](https://user-images.githubusercontent.com/4063528/119811415-eb310a00-be9b-11eb-80d3-db46e3a2fdb0.png)

* Which operating system and web browser you are using
*Windows 10 Home, Google Chrome and Microsoft Edge*
* When the issue started happening
*on first login to pro*
* What steps we would need to take to replicate the issue
*clear all browsing data and login again*
* Any errors you can see
*none*

**Comment by jesshewitt** [comment]
Thanks for the report! I'll check it out.

**Comment by jesshewitt** [comment]
Fixed...will be in the next release.
